from django.urls import path
from .routes.policy import (
    framework_list, framework_detail, policy_detail, policy_list,
    add_policy_to_framework, add_subpolicy_to_policy, 
    subpolicy_detail, copy_framework, copy_policy,
    create_framework_version, create_policy_version,
    export_policies_to_excel,
    update_policy_approval,
    submit_policy_review,
    # list_rejected_policy_approvals_for_user,
    resubmit_policy_approval,
    list_users,
    get_framework_explorer_data,
    get_framework_policies,
    toggle_framework_status,
    toggle_policy_status,
    get_framework_details,
    get_policy_details,
    all_policies_get_frameworks,
    all_policies_get_framework_versions,
    all_policies_get_framework_version_policies,
    all_policies_get_policies,
    all_policies_get_policy_versions,
    all_policies_get_subpolicies,
    all_policies_get_policy_version_subpolicies,
    all_policies_get_subpolicy_details,
    get_policy_dashboard_summary,
    get_policy_status_distribution,
    get_reviewer_workload,
    get_recent_policy_activity,
    get_avg_policy_approval_time,
    get_policy_analytics,
    get_policy_kpis,
    acknowledge_policy,
    get_policies_by_framework,
    get_subpolicies_by_policy,  
    get_latest_policy_approval,
    get_latest_policy_approval_by_role,
    get_latest_reviewer_version,
    submit_subpolicy_review,
    resubmit_subpolicy,
    get_policy_version,
    get_subpolicy_version,
    submit_policy_approval_review,
    get_policy_version_history,
    list_policy_approvals_for_reviewer,
    list_rejected_policy_approvals_for_user
)
from .routes.frameworks import (
    create_framework_approval,
    get_framework_approvals,
    update_framework_approval,
    submit_framework_review,
    get_latest_framework_approval,
    resubmit_framework
)

urlpatterns = [
    path('frameworks/', framework_list, name='framework-list'),
    path('frameworks/<int:pk>/', framework_detail, name='framework-detail'),
    path('frameworks/<int:pk>/copy/', copy_framework, name='copy-framework'),
    path('frameworks/<int:pk>/create-version/', create_framework_version, name='create-framework-version'),
    path('frameworks/<int:framework_id>/export/', export_policies_to_excel, name='export-framework-policies'),
    path('policies/', policy_list, name='policy-list'),
    path('policies/<int:pk>/', policy_detail, name='policy-detail'),
    path('policies/<int:pk>/copy/', copy_policy, name='copy-policy'),
    path('policies/<int:pk>/create-version/', create_policy_version, name='create-policy-version'),
    path('subpolicies/<int:pk>/', subpolicy_detail, name='subpolicy-detail'),
    path('api/frameworks/<int:framework_id>/policies/', add_policy_to_framework, name='add-policy-to-framework'),
    path('policies/<int:policy_id>/subpolicies/', add_subpolicy_to_policy, name='add-subpolicy-to-policy'),
    path('api/subpolicies/<int:pk>/review/', submit_subpolicy_review, name='submit-subpolicy-review'),
    path('api/subpolicies/<int:pk>/resubmit/', resubmit_subpolicy, name='resubmit-subpolicy'),
    path('api/policy-approvals/reviewer/', list_policy_approvals_for_reviewer, name='policy-approvals-for-reviewer'),
    path('api/policy-approvals/<int:approval_id>/', update_policy_approval, name='update_policy_approval'),
    path('api/policy-approvals/<int:approval_id>/review/', submit_policy_review, name='submit_policy_review'),
    path('api/policy-approvals/rejected/<int:user_id>/', list_rejected_policy_approvals_for_user),
    path('api/policy-approvals/resubmit/<int:approval_id>/', resubmit_policy_approval),
    path('api/users/', list_users, name='list-users'),
    path('api/framework-explorer/', get_framework_explorer_data, name='framework-explorer'),
    path('api/frameworks/<int:framework_id>/policies-list/', get_framework_policies, name='framework-policies'),
    path('api/frameworks/<int:framework_id>/toggle-status/', toggle_framework_status, name='toggle-framework-status'),
    path('api/policies/<int:policy_id>/toggle-status/', toggle_policy_status, name='toggle-policy-status'),
    path('api/frameworks/<int:framework_id>/details/', get_framework_details, name='framework-details'),
    path('api/policies/<int:policy_id>/details/', get_policy_details, name='policy-details'),
    path('api/all-policies/frameworks/', all_policies_get_frameworks, name='all-policies-frameworks'),
    path('api/all-policies/frameworks/<int:framework_id>/versions/', all_policies_get_framework_versions, name='all-policies-framework-versions'),
    path('api/all-policies/framework-versions/<int:version_id>/policies/', all_policies_get_framework_version_policies, name='all-policies-framework-version-policies'),
    path('api/all-policies/policies/', all_policies_get_policies, name='all-policies-policies'),
    path('api/all-policies/policies/<int:policy_id>/versions/', all_policies_get_policy_versions, name='all-policies-policy-versions'),
    path('api/all-policies/subpolicies/', all_policies_get_subpolicies, name='all-policies-subpolicies'),
    path('api/all-policies/policy-versions/<int:version_id>/subpolicies/', all_policies_get_policy_version_subpolicies, name='all-policies-policy-version-subpolicies'),
    path('api/all-policies/subpolicies/<int:subpolicy_id>/', all_policies_get_subpolicy_details, name='all-policies-subpolicy-details'),
    path('api/policy-dashboard/', get_policy_dashboard_summary),
    path('api/policy-status-distribution/', get_policy_status_distribution),
    path('api/reviewer-workload/', get_reviewer_workload),
    path('api/recent-policy-activity/', get_recent_policy_activity),
    path('api/avg-policy-approval-time/', get_avg_policy_approval_time),
    path('api/policy-analytics/', get_policy_analytics, name='policy-analytics'),
    path('policy-analytics/', get_policy_analytics),
    path('api/policy-kpis/', get_policy_kpis),    
    path('api/acknowledge-policy/<int:policy_id>/', acknowledge_policy, name='acknowledge-policy'),      
    path('api/frameworks/<int:framework_id>/get-policies/', get_policies_by_framework, name='get-policies-by-framework'),
    path('api/policies/<int:policy_id>/get-subpolicies/', get_subpolicies_by_policy, name='get-subpolicies-by-policy'),
    path('api/policies/<int:policy_id>/version/', get_policy_version, name='get-policy-version'),
    path('api/subpolicies/<int:subpolicy_id>/version/', get_subpolicy_version, name='get-subpolicy-version'),
    path('api/policy-approvals/latest/<int:policy_id>/', get_latest_policy_approval, name='get-latest-policy-approval'),
    path('api/policy-approvals/latest-by-role/<int:policy_id>/<str:role>/', get_latest_policy_approval_by_role, name='get-latest-policy-approval-by-role'),
    path('api/policies/<int:policy_id>/reviewer-version/', get_latest_reviewer_version, name='get-policy-reviewer-version'),
    path('api/policies/<int:policy_id>/submit-review/', submit_policy_approval_review, name='submit-policy-approval-review'),
    path('api/policies/<int:policy_id>/version-history/', get_policy_version_history, name='get-policy-version-history'),
    path('api/frameworks/<int:framework_id>/create-approval/', create_framework_approval, name='create-framework-approval'),
    path('api/framework-approvals/', get_framework_approvals, name='get-framework-approvals'),
    path('api/framework-approvals/<int:framework_id>/', get_framework_approvals, name='get-framework-approvals-by-id'),
    path('api/framework-approvals/<int:approval_id>/update/', update_framework_approval, name='update-framework-approval'),
    path('api/frameworks/<int:framework_id>/submit-review/', submit_framework_review, name='submit-framework-review'),
    path('api/framework-approvals/latest/<int:framework_id>/', get_latest_framework_approval, name='get-latest-framework-approval'),
    path('api/frameworks/<int:framework_id>/resubmit/', resubmit_framework, name='resubmit-framework')
]