# Generated by Django 5.2.1 on 2025-05-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compliance",
            fields=[
                ("SubPolicyId", models.IntegerField()),
                ("ComplianceId", models.AutoField(primary_key=True, serialize=False)),
                ("ComplianceItemDescription", models.TextField(null=True)),
                ("IsRisk", models.BooleanField(null=True)),
                ("PossibleDamage", models.TextField(null=True)),
                ("Criticality", models.CharField(max_length=50, null=True)),
                ("MandatoryOptional", models.CharField(max_length=50, null=True)),
                ("ManualAutomatic", models.CharField(max_length=50, null=True)),
                ("Impact", models.CharField(max_length=50, null=True)),
                ("Probability", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "compliance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RiskApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RiskInstanceId", models.IntegerField()),
                ("version", models.CharField(max_length=45)),
                ("ExtractedInfo", models.JSONField(null=True)),
                ("UserId", models.CharField(max_length=45, null=True)),
                ("ApproverId", models.CharField(max_length=45, null=True)),
                ("ApprovedRejected", models.CharField(max_length=45, null=True)),
                ("Date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "grc.risk_approval",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GRCLog",
            fields=[
                ("LogId", models.AutoField(primary_key=True, serialize=False)),
                ("Timestamp", models.DateTimeField(auto_now_add=True)),
                ("UserId", models.CharField(max_length=50, null=True)),
                ("UserName", models.CharField(max_length=100, null=True)),
                ("Module", models.CharField(max_length=100, null=True)),
                ("ActionType", models.CharField(max_length=50, null=True)),
                ("EntityId", models.CharField(max_length=50, null=True)),
                ("EntityType", models.CharField(max_length=50, null=True)),
                ("LogLevel", models.CharField(default="INFO", max_length=20)),
                ("Description", models.TextField(null=True)),
                ("IPAddress", models.CharField(max_length=45, null=True)),
                ("AdditionalInfo", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "grc_logs",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("IncidentId", models.AutoField(primary_key=True, serialize=False)),
                ("IncidentTitle", models.CharField(max_length=255, null=True)),
                ("Description", models.TextField(null=True)),
                ("Mitigation", models.TextField(null=True)),
                ("AuditId", models.IntegerField(null=True)),
                ("ComplianceId", models.IntegerField(null=True)),
                ("Date", models.DateField(null=True)),
                ("Time", models.TimeField(null=True)),
                ("UserId", models.IntegerField(null=True)),
                ("Origin", models.CharField(max_length=50, null=True)),
                ("Comments", models.TextField(null=True)),
                ("RiskCategory", models.CharField(max_length=100, null=True)),
                ("RiskPriority", models.CharField(max_length=20, null=True)),
                ("Attachments", models.TextField(null=True)),
                ("CreatedAt", models.DateTimeField(null=True)),
                ("Status", models.CharField(max_length=45, null=True)),
                ("IdentifiedAt", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "incidents",
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("RiskId", models.AutoField(primary_key=True, serialize=False)),
                ("ComplianceId", models.IntegerField(null=True)),
                ("Criticality", models.CharField(max_length=100, null=True)),
                ("PossibleDamage", models.TextField(null=True)),
                ("Category", models.CharField(max_length=100, null=True)),
                ("RiskDescription", models.TextField(null=True)),
                ("RiskLikelihood", models.CharField(max_length=50, null=True)),
                ("RiskImpact", models.CharField(max_length=50, null=True)),
                ("RiskExposureRating", models.CharField(max_length=50, null=True)),
                ("RiskPriority", models.CharField(max_length=50, null=True)),
                ("RiskMitigation", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "risk",
            },
        ),
        migrations.CreateModel(
            name="RiskInstance",
            fields=[
                ("RiskInstanceId", models.AutoField(primary_key=True, serialize=False)),
                ("RiskId", models.IntegerField(null=True)),
                ("IncidentId", models.IntegerField(null=True)),
                ("Criticality", models.CharField(max_length=100, null=True)),
                ("PossibleDamage", models.TextField(null=True)),
                ("Category", models.CharField(max_length=100, null=True)),
                ("Appetite", models.CharField(max_length=100, null=True)),
                ("RiskDescription", models.TextField(null=True)),
                ("RiskLikelihood", models.CharField(max_length=50, null=True)),
                ("RiskImpact", models.CharField(max_length=50, null=True)),
                ("RiskExposureRating", models.CharField(max_length=50, null=True)),
                ("RiskPriority", models.CharField(max_length=50, null=True)),
                ("RiskResponseType", models.CharField(max_length=100, null=True)),
                ("RiskResponseDescription", models.TextField(null=True)),
                ("RiskMitigation", models.JSONField(blank=True, null=True)),
                ("RiskOwner", models.CharField(max_length=255, null=True)),
                (
                    "RiskStatus",
                    models.CharField(
                        choices=[
                            ("Not Assigned", "Not Assigned"),
                            ("Assigned", "Assigned"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Not Assigned",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "MitigationStatus",
                    models.CharField(
                        choices=[
                            ("Yet to Start", "Yet to Start"),
                            ("Work In Progress", "Work In Progress"),
                            (
                                "Revision Required by Reviewer",
                                "Revision Required by Reviewer",
                            ),
                            ("Revision Required by User", "Revision Required by User"),
                            ("Completed", "Completed"),
                        ],
                        default="Yet to Start",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("UserId", models.IntegerField(null=True)),
                ("Date", models.DateTimeField(null=True)),
                ("MitigationDueDate", models.DateTimeField(null=True)),
                ("MitigationCompletedDate", models.DateTimeField(null=True)),
                ("ModifiedMitigations", models.JSONField(null=True)),
                ("ReviewerCount", models.IntegerField(null=True)),
                ("RiskFormDetails", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "risk_instance",
            },
        ),
        migrations.CreateModel(
            name="RiskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="grc.risk",
                    ),
                ),
            ],
        ),
    ]
