# Generated by Django 5.2.1 on 2025-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('sub_policy_id', models.IntegerField(blank=True, null=True)),
                ('compliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('compliance_item_description', models.TextField(blank=True, null=True)),
                ('is_risk', models.BooleanField(default=False)),
                ('possible_damage', models.TextField(blank=True, null=True)),
                ('criticality', models.CharField(blank=True, max_length=50, null=True)),
                ('mandatory_optional', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_automatic', models.CharField(blank=True, max_length=50, null=True)),
                ('impact', models.CharField(blank=True, max_length=50, null=True)),
                ('probability', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
