# Generated by Django 5.2.1 on 2025-05-11 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('duedate', models.DateField()),
                ('frequency', models.IntegerField(null=True)),
                ('audit_type', models.CharField(max_length=1)),
                ('assignee', models.ForeignKey(db_column='assignee', on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(db_column='auditor', on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(db_column='reviewer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.CreateModel(
            name='AuditFindings',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('check_status', models.CharField(choices=[('0', 'Unchecked'), ('1', 'Checked'), ('2', 'Reviewed')], max_length=1)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('audit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.audit')),
            ],
            options={
                'db_table': 'audit_findings',
            },
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('SubPolicyId', models.IntegerField()),
                ('ComplianceId', models.IntegerField(primary_key=True, serialize=False)),
                ('ComplianceItemDescription', models.TextField()),
                ('IsRisk', models.BooleanField()),
                ('PossibleDamage', models.TextField()),
                ('Criticality', models.CharField(max_length=50)),
                ('MandatoryOptional', models.CharField(max_length=50)),
                ('ManualAutomatic', models.CharField(max_length=50)),
                ('Impact', models.CharField(max_length=50)),
                ('Probability', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'compliance',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('FrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkName', models.CharField(max_length=255)),
                ('Version', models.CharField(max_length=50)),
                ('FrameworkDetails', models.TextField()),
                ('Date', models.DateField()),
                ('CreatedByName', models.CharField(max_length=255)),
                ('CreatedByDate', models.DateField()),
                ('AuthorisedByName', models.CharField(max_length=255)),
                ('AuthorisedByDate', models.DateField()),
                ('Category', models.CharField(max_length=50)),
                ('DocURL', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=45)),
                ('Authorized_Description', models.CharField(max_length=255)),
                ('Authorized_Title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'frameworks',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('IncidentId', models.AutoField(primary_key=True, serialize=False)),
                ('incidenttitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Origin', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
                ('risk_category', models.CharField(max_length=100)),
                ('priority_level', models.CharField(max_length=20)),
                ('attachments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ComplianceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.compliance')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='LastChecklistItemVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Complied', models.CharField(max_length=1)),
                ('Comments', models.TextField()),
                ('ComplianceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.compliance')),
                ('FrameworkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.framework')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lastchecklistitemverified',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('PolicyId', models.AutoField(primary_key=True, serialize=False)),
                ('PolicyName', models.CharField(max_length=255)),
                ('FrameworkId', models.ForeignKey(db_column='FrameworkId', on_delete=django.db.models.deletion.CASCADE, to='grc.framework')),
            ],
            options={
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('RiskId', models.AutoField(primary_key=True, serialize=False)),
                ('Origin', models.CharField(max_length=50)),
                ('Criticality', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Category', models.TextField()),
                ('appetite', models.TextField()),
                ('ComplianceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.compliance')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='SubPolicy',
            fields=[
                ('Version', models.CharField(max_length=50)),
                ('SubPolicyId', models.IntegerField(primary_key=True, serialize=False)),
                ('SubPolicyName', models.CharField(max_length=255)),
                ('CreatedByName', models.CharField(max_length=255)),
                ('CreatedByDate', models.DateField()),
                ('AuthorisedByName', models.CharField(max_length=255)),
                ('AuthorisedByDate', models.DateField()),
                ('Applicability', models.CharField(max_length=45)),
                ('identifier', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('PolicyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.policy')),
            ],
            options={
                'db_table': 'subpolicies',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('role', models.CharField(max_length=45)),
                ('branch', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='GRCProfile',
        ),
        migrations.AddField(
            model_name='auditfindings',
            name='ComplianceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.compliance'),
        ),
        migrations.AddField(
            model_name='audit',
            name='FrameworkId',
            field=models.ForeignKey(db_column='FrameworkId', on_delete=django.db.models.deletion.CASCADE, to='grc.framework'),
        ),
        migrations.AddField(
            model_name='incident',
            name='audit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.audit'),
        ),
        migrations.AddField(
            model_name='lastchecklistitemverified',
            name='PolicyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.policy'),
        ),
        migrations.AddField(
            model_name='audit',
            name='PolicyId',
            field=models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.CASCADE, to='grc.policy'),
        ),
        migrations.AddField(
            model_name='risk',
            name='IncidentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.incident'),
        ),
        migrations.AddField(
            model_name='risk',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='audit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.audit'),
        ),
        migrations.AddField(
            model_name='lastchecklistitemverified',
            name='SubPolicyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.subpolicy'),
        ),
    ]
