# Generated by Django 5.0.1 on 2025-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('FrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkName', models.CharField(blank=True, max_length=255, null=True)),
                ('Version', models.CharField(blank=True, max_length=50, null=True)),
                ('FrameworkDetails', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('AuthorisedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('AuthorisedByDate', models.DateField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GRCProfile',
        ),
    ]
