# Generated by Django 5.2.1 on 2025-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='ApprovalStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='ApprovalStatus', default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='compliance_id',
            field=models.AutoField(db_column='ComplianceId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='compliance_item_description',
            field=models.TextField(blank=True, db_column='ComplianceItemDescription', null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='criticality',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_column='Criticality', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='impact',
            field=models.CharField(blank=True, db_column='Impact', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='is_risk',
            field=models.BooleanField(db_column='IsRisk', default=False),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='mandatory_optional',
            field=models.CharField(blank=True, choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], db_column='MandatoryOptional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='manual_automatic',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], db_column='ManualAutomatic', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='possible_damage',
            field=models.TextField(blank=True, db_column='PossibleDamage', null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='probability',
            field=models.CharField(blank=True, db_column='Probability', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='sub_policy_id',
            field=models.IntegerField(blank=True, db_column='SubPolicyId', null=True),
        ),
        migrations.AlterModelTable(
            name='compliance',
            table='compliance',
        ),
    ]
