# Generated by Django 5.0.1 on 2025-05-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_framework_delete_grcprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='framework',
            table='framework',
        ),
    ]
