# Generated by Django 5.0.1 on 2025-05-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0003_alter_framework_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='framework',
            table='frameworks',
        ),
    ]
