# Generated by Django 5.2.1 on 2025-05-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0003_compliance_approvalstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('FrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkName', models.CharField(max_length=255)),
                ('CurrentVersion', models.FloatField(blank=True, null=True)),
                ('FrameworkDescription', models.TextField(blank=True, null=True)),
                ('EffectiveDate', models.DateField()),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('Identifier', models.CharField(blank=True, max_length=45, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=45, null=True)),
                ('ActiveInactive', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'frameworks',
            },
        ),
        migrations.CreateModel(
            name='FrameworkVersion',
            fields=[
                ('FrameworkVersionId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.framework')),
            ],
        ),
        migrations.DeleteModel(
            name='Compliance',
        ),
    ]
