# Generated by Django 5.0.1 on 2025-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_alter_framework_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('FrameworkId', models.IntegerField(blank=True, null=True)),
                ('PolicyId', models.IntegerField(primary_key=True, serialize=False)),
                ('Version', models.CharField(max_length=50)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PolicyDetails', models.TextField(blank=True, null=True)),
                ('PolicyName', models.CharField(max_length=255)),
                ('EffectiveStartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('AuthorisedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('AuthorisedByDate', models.DateField(blank=True, null=True)),
                ('Applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'policies',
            },
        ),
    ]
