# Generated by Django 5.2.1 on 2025-05-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_framework_frameworkversion_delete_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('PolicyId', models.AutoField(primary_key=True, serialize=False)),
                ('CurrentVersion', models.FloatField()),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PolicyDescription', models.TextField(blank=True, null=True)),
                ('PolicyName', models.CharField(max_length=255)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('Applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('Scope', models.TextField(blank=True, null=True)),
                ('Objective', models.TextField(blank=True, null=True)),
                ('Identifier', models.CharField(blank=True, max_length=45, null=True)),
                ('PermanentTemporary', models.CharField(blank=True, max_length=45, null=True)),
                ('ActiveInactive', models.CharField(blank=True, max_length=45, null=True)),
                ('FrameworkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='grc.framework')),
            ],
            options={
                'db_table': 'policies',
            },
        ),
    ]
