# Generated by Django 5.2.1 on 2025-05-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0005_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPolicy',
            fields=[
                ('SubPolicyId', models.AutoField(primary_key=True, serialize=False)),
                ('SubPolicyName', models.CharField(max_length=255)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('Identifier', models.CharField(blank=True, max_length=45, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PermanentTemporary', models.CharField(blank=True, max_length=50, null=True)),
                ('Control', models.TextField(blank=True, null=True)),
                ('PolicyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpolicies', to='grc.policy')),
            ],
            options={
                'db_table': 'subpolicies',
            },
        ),
    ]
