# Generated by Django 5.0.1 on 2025-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0005_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyId', models.IntegerField()),
                ('Version', models.CharField(max_length=50)),
                ('SubPolicyId', models.IntegerField()),
                ('SubPolicyName', models.CharField(max_length=255)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('AuthorisedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('AuthorisedByDate', models.DateField(blank=True, null=True)),
                ('Applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subpolicies',
                'unique_together': {('PolicyId', 'Version', 'SubPolicyId')},
            },
        ),
    ]
