# Generated by Django 5.0.1 on 2025-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0006_subpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpolicy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
