# Generated by Django 5.2.1 on 2025-05-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0006_subpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('ComplianceId', models.AutoField(primary_key=True, serialize=False)),
                ('ComplianceName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('DueDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedByDate', models.DateField(blank=True, null=True)),
                ('SubPolicyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='grc.subpolicy')),
            ],
            options={
                'db_table': 'compliances',
            },
        ),
    ]
