# Generated by Django 5.0.1 on 2025-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0007_alter_subpolicy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpolicy',
            name='id',
        ),
        migrations.AlterField(
            model_name='subpolicy',
            name='SubPolicyId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
