name: CI Pipeline

on:
  push:
    branches:
      - main
      - CI/CD-Pipeline  # Add your actual branch
  pull_request:
    branches:
      - main
      - CI/CD-Pipeline  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Lint Backend Code
        run: |
          pip install flake8
          flake8 grc  # Pointing to your actual folder

      - name: Run Backend Tests
        run: |
          pip install pytest
          pytest grc/tests  # Update path if needed

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm run test

      - name: Run Snyk Scan
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test
