name: CI Pipeline

# Trigger on push or pull requests to main and CI/CD-Pipeline branches1
on:
  push:
    branches:
      - main
      - Test
  pull_request:
    branches:
      - main
      - Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Ensure the correct path if needed


