#ci-pipeline

name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest for testing

    - name: Run Hello World test
      run: |
        echo "print('Hello, World!')" > hello_world.py  # Creating the hello world file
        python hello_world.py  # Running the python file

    - name: Run unit tests
      run: |
        pytest hello_world.py  # Running pytest to ensure everything works
