name: CI Pipeline

on:
  push:
    branches:
      - main
      - CI/CD-Pipeline
  pull_request:
    branches:
      - main
      - CI/CD-Pipeline

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Backend Dependencies (ensure the correct path to requirements.txt)
      - name: Install Backend Dependencies
        run: |
          cd backend  # Navigate to the 'backend' directory if required
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Frontend Dependencies (if necessary)
      - name: Install Frontend Dependencies
        run: |
          cd frontend  # If the frontend dependencies are in 'frontend/package.json'
          npm install

      # Run Linting for Python Code
      - name: Lint Python Code
        run: |
          pip install flake8
          flake8 src  # Assuming your backend Python code is in the 'src' directory

      # Run Unit Tests for Python (from 'tests' folder)
      - name: Run Unit Tests
        run: |
          pip install pytest  # Install pytest
          pytest tests  # Run all tests in the 'tests' directory

      # Run Snyk Dependency Scan
      - name: Run Snyk Dependency Scan
        uses: snyk/actions/python@master
        with:
          args: --file=backend/requirements.txt  # Ensure correct path
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Install and run Snyk Code Scan
      - name: Install Snyk CLI for Code Scan
        uses: snyk/actions/setup@master

      - name: Run Snyk Code Scan
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
