name: CI Pipeline

# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
      - CI/CD-Pipeline
  pull_request:
    branches:
      - main
      - CI/CD-Pipeline

jobs:
  test:
    runs-on: ubuntu-latest

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Ensure the correct path if needed


     
