name: CI Pipeline

# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
      - CI/CD-Pipeline
  pull_request:
    branches:
      - main
      - CI/CD-Pipeline

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
            pip install -r requirements.txt  # Backend
            npm install  # Frontend (if applicable)


     
