name: E2E Tests

on:
  push:
    branches:
      - Risk_test1
  pull_request:
    branches:
      - Risk_test1

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Install serve globally
        run: npm install -g serve

      - name: Start frontend server in background
        run: nohup serve -s ./frontend/dist -l 5000 > serve.log 2>&1 &

      - name: Wait for server to be ready
        run: |
          echo "Waiting for http://localhost:5000 to be ready..."
          for i in {1..24}; do
            if curl --silent --fail http://localhost:5000; then
              echo "Server is up!"
              exit 0
            else
              echo "Server not ready yet, waiting 5 seconds..."
              sleep 5
            fi
          done
          echo "Server did not start within 2 minutes."
          exit 1

      - name: Run Cypress tests
        run: npm run cypress:run
        working-directory: ./frontend

      - name: Upload Cypress videos and screenshots (optional)
        if: failure()
        uses: actions/upload-artifact@v2

        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
