name: E2E Tests

on:
  push:
    branches:
      - Risk_test1
  pull_request:
    branches:
      - Risk_test1

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Install serve globally
        run: npm install -g serve

      - name: Start frontend server in background
        run: nohup serve -s ./frontend/dist -l 5000 > serve.log 2>&1 &

      - uses: softprops/wait-on@v1.1.0
        with:
          url: http://localhost:5000
          timeout: '120000'  # timeout in milliseconds


      - name: Run Cypress tests
        run: npm run cypress:run
        working-directory: ./frontend

      - name: Upload Cypress videos and screenshots (optional)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
