name: Run Unit Tests for GRC Project

on:
  push:
    branches:
      - main
      - Test
  pull_request:
    branches:
      - main
      - Test

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies for backend
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run unit tests for Django (backend)
        run: pytest grc/ --maxfail=1 --disable-warnings -v
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use LTS or your preferred version

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies for frontend
        run: npm install
        working-directory: frontend

      - name: Run unit tests for Vue.js (frontend)
        run: npm run test
        working-directory: frontend
